environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "boost.build/1.64.0"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_STABLE_BRANCH_PATTERN: "stable/*"
    CONAN_TOTAL_PAGES: 1   

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 1
          CONAN_ARCHS: x86_64

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          # CONAN_VISUAL_VERSIONS: 15
          # CONAN_CURRENT_PAGE: 2
          # CONAN_ARCHS: x86_64

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          # CONAN_VISUAL_VERSIONS: 15
          # CONAN_CURRENT_PAGE: 1
          # CONAN_ARCHS: x86

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          # CONAN_VISUAL_VERSIONS: 15
          # CONAN_CURRENT_PAGE: 2
          # CONAN_ARCHS: x86

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          # CONAN_VISUAL_VERSIONS: 14
          # CONAN_CURRENT_PAGE: 1
          # CONAN_ARCHS: x86_64

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          # CONAN_VISUAL_VERSIONS: 14
          # CONAN_CURRENT_PAGE: 2
          # CONAN_ARCHS: x86_64

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          # CONAN_VISUAL_VERSIONS: 14
          # CONAN_CURRENT_PAGE: 1
          # CONAN_ARCHS: x86

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          # CONAN_VISUAL_VERSIONS: 14
          # CONAN_CURRENT_PAGE: 2
          # CONAN_ARCHS: x86

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          # CONAN_VISUAL_VERSIONS: 12
          # CONAN_CURRENT_PAGE: 1
          # CONAN_ARCHS: x86_64

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          # CONAN_VISUAL_VERSIONS: 12
          # CONAN_CURRENT_PAGE: 2
          # CONAN_ARCHS: x86_64

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          # CONAN_VISUAL_VERSIONS: 12
          # CONAN_CURRENT_PAGE: 1
          # CONAN_ARCHS: x86

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          # CONAN_VISUAL_VERSIONS: 12
          # CONAN_CURRENT_PAGE: 2
          # CONAN_ARCHS: x86

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user
  - conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
  - conan remote add_ref Boost.Build/1.64.0@bincrafters/testing bincrafters

build_script:
  - conan create Boost.Build/testing
#test_script:
 # - python build.py